### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by okm404** [dds2333/atexec_sharp#1]
如何使用呢，
![image](https://user-images.githubusercontent.com/42562811/142271704-45e06278-8f13-49cf-998a-ab5bf21c7aa7.png)

**Comment by dds2333** [comment]
忘记将 dll 嵌入 exe 了，我上传了新版本🤣；也可根据项目源代码代码自己编译一个

**Comment by dds2333** [comment]
> 如何使用呢， ![image](https://user-images.githubusercontent.com/42562811/142271704-45e06278-8f13-49cf-998a-ab5bf21c7aa7.png)

忘记将 dll 嵌入 exe 了，我上传了新版本🤣；也可根据项目源代码代码自己编译一个

**Comment by AshvinGudaliya** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @ventura-lepgs, @mikayelagh, @0xfeeddeadbeef, @knockshore, @AlphaGhostUSMC, @appfromape, @Suryadevelops, @PureChaos001, @0x-maker, @markzyu, @Peachy-eyes, @marcusvwagner, @rgdzh1, @maikzz, @djangoleonard, @a186r, @XiangQingW, @yycmmc, @ibjb33, @Mugan-Jin
